### ISSUE TITLE
RFE - Explain what bigrest does

### ISSUE THREAD

**Issue by rtfmoz2** [leonardobdes/BIGREST#1]
Hi, what does this actually provide? I know it provides some things that apparently make it easier to work with both BIGIP and BIGIQ but more examples are needed. The reason behind its creation.... to provide a unified REST API to BIG-IP products perhaps?

**Comment by leonardobdes** [comment]
Documentation updated with "What is useful for?" and "Why create another SDK?" sections.

https://bigrest.readthedocs.io/introduction.html
