### ISSUE TITLE
RESTAPIError on connect, /mgmt/shared/echo-query is not guaranteed to exist

### ISSUE THREAD

**Issue by rahvee** [leonardobdes/BIGREST#17]
BIGREST Version: 1.4.0
BIG-IP Version: 14.1.4.6 Build 0.0.8

To replicate bug, simply try to create an instance of the BIGIP class
`bigip = BIGIP(hostname, username, password)`

stack trace:

    _connect, big.py:491
    __init__, big.py:91
    __init__, bigip.py:40

The issue is line 491. During `_connect()`, BIGIP tries to `GET` on `f"https://{self.device}/mgmt/shared/echo-query"`
In my version of BIG-IP, this URL does not exist. My response status code is 401, so BIGIP will `raise RESTAPIError` on line 493.

The solution is simple (at least for me). Just get rid of the `mgmt/shared/echo-query` from the URL. Use this URL instead:
`f"https://{self.device}/`

This returns a 200 status, so everything works.

My change is here:
https://github.com/rahvee/BIGREST/commit/f535bfaec341741f90bd0c90cd21f60ebad628a3

This change works for me. I don't have the ability to test on any other system (different versions of Big-IP, IQ), so I didn't submit it as a pull request for you.

**Comment by leonardobdes** [comment]
The path `/mgmt/shared/echo-query` exists, as you can see in these tests.

```
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bigrest.bigip import BIGIP
>>> device = BIGIP("192.168.255.2","bigrest", "bigrest", session_verify=False)
>>> print(device.show("/mgmt/tm/sys/version"))
{
    "Build": {
        "description": "0.0.8"
    },
    "Date": {
        "description": "Mon Mar 28 02:38:32 PDT 2022"
    },
    "Edition": {
        "description": "Point Release 6"
    },
    "Product": {
        "description": "BIG-IP"
    },
    "Title": {
        "description": "Main Package"
    },
    "Version": {
        "description": "14.1.4.6"
    }
}
>>> device2 = BIGIP("192.168.255.2","bigrest", "bigrest", session_verify=False, request_token=True)
>>> print(device2.show("/mgmt/tm/sys/version"))
{
    "Build": {
        "description": "0.0.8"
    },
    "Date": {
        "description": "Mon Mar 28 02:38:32 PDT 2022"
    },
    "Edition": {
        "description": "Point Release 6"
    },
    "Product": {
        "description": "BIG-IP"
    },
    "Title": {
        "description": "Main Package"
    },
    "Version": {
        "description": "14.1.4.6"
    }
}
>>> 
```
As you can see in the solution:
[K59960390](https://support.f5.com/csp/article/K59960390)
Bug IDs  [ID 1025513](https://cdn.f5.com/product/bugtracker/ID1025513.html) and [ID 1035661](https://cdn.f5.com/product/bugtracker/ID1035661.html) seem to apply to your case and version.
I also had the same 401 error during my tests, so restarting both restjavad and restnoded made it work again.
To avoid the bug, just use the request_token option.
