### ISSUE TITLE
Can you put bundle this version of BIGREST into a release?

### ISSUE THREAD

**Issue by roberto0180** [leonardobdes/BIGREST#23]
We would like to use this package but our security team won't allow it unless it is bundled into a release and has a direct download to a specific version. It should only take a couple of minutes to do: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by leonardobdes** [comment]
Sorry for the long delay.
Done: [https://github.com/leonardobdes/BIGREST/releases](https://github.com/leonardobdes/BIGREST/releases)
