### ISSUE TITLE
Max retries exceeded with url: /mgmt/shared/echo-query (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f376b97a4d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

### ISSUE THREAD

**Issue by jjarboe23** [leonardobdes/BIGREST#25]
In writing a script to go through our 85 F5 instances to build an inventory with VS, pool, node, and SSL information returned, we find the iControlREST times out on occasion.  Rather than have the whole script fail, we want it to continue processing as if no data was received.  

I have edited big.py to encapsulate the "response = self.session.get(url, timeout=self.timeout) with a try statement, and if it fails to connect, the except sets response = ''

I have done this in the load and show definitions of big.py file.  Hopefully this will be helpful to others vs writing all kinds of error handling into your main script.

**Comment by leonardobdes** [comment]
That is one option, but I think you can do that without changing BIGREST internally.
Just use a try block every time you create an object type "BIGIP".

If you want to handle the exceptions that BIGREST can raise from that, they are:
InvalidOptionError: Raised when invalid options are used as arguments.
RESTAPIError: Raised when iControl REST API returns an error.

BIGREST uses [requests](https://requests.readthedocs.io/en/latest/) internally.
Requests internally uses [urllib3](https://urllib3.readthedocs.io/en/stable/).
These can all raise exceptions, including all other libraries they use.
