### ISSUE TITLE
Add pytest framework to automate tests for development efforts / version changes

### ISSUE THREAD

**Issue by f5-rahm** [leonardobdes/BIGREST#6]
I will be working on this one for a while. Goal is to use pytest to:

- test python version compatibility
- test python style compliance
- test BIG-IP version compatibility
- test BIG-IQ version compatibility

**Comment by leonardobdes** [comment]
- test python version compatibility
I used these:
https://pypi.org/project/vermin/
https://github.com/ghewgill/pyqver

However, as far as I remember, it was saying version 3.6.
However, I knew I was using new features from 3.7, so can't just use what these tools say.

- test python style compliance

I used these:
https://gitlab.com/pycqa/flake8
https://github.com/klen/pylama/

They wrap other tools.

- test BIG-IP version compatibility

I tested with 12.0.0 and a newer version (I think was 15.1.0).
In theory, should work with any version, but 11.6.0 or above had some API changes, so not a good idea to use those versions.
If you find an automated way to test in every version, that would catch some bugs that are version-specific, and we could work around them if possible.

- test BIG-IQ version compatibility

I just tested in 7.1.0 (or 7.0.0, I don't remember).

- pytest
I looked at this but did not do what I wanted.
Anyway, if you can make it do the job that is been done by the scripts in the /tests folder, that is fine.

**Comment by leonardobdes** [comment]
Closing this, as it has been open for a while.
