### ISSUE TITLE
BIGREST returns errors on successful calls

### ISSUE THREAD

**Issue by leaficier** [leonardobdes/BIGREST#8]
BIGREST seems to consider only the 200 code as a successful request. Should be updated to include the other successful codes (201, 202, etc).

https://github.com/leonardobdes/BIGREST/blob/926a89da313f9abf215f8b36c08317674e882c24/bigrest/big.py#L112

Example:

```
Traceback (most recent call last):
  File "XXXX.py", line 52, in <module>
    create = device.create(f'/mgmt/tm/asm/policies/{rest_format(policyId)}/whitelist-ips', whitelist_settings)
  File "/home/nick/.local/lib/python3.8/site-packages/bigrest/big.py", line 184, in create
    raise RESTAPIError(response, self.debug)
bigrest.common.exceptions.RESTAPIError: 
Status:
201
Response Body:
{
    "ignoreIpReputation": true,
    "blockRequests": "never",
    "ignoreAnomalies": false,
    "neverLogRequests": true,
 …
}
```

**Comment by leonardobdes** [comment]
I just had quick look and there is also 202 and 206, but not 201.
I am thinking if I should fix just adding 201 for this case, or is better just to consider any 2xx valid.
I will review the code and think about it.

**Comment by leonardobdes** [comment]
I decided to just add 201 to the create method.
Fix for this bug included in version 1.3.2.

**Comment by lrhazi** [comment]
I am seeing this same issue in current version: 1.7.3. exception RESTAPIError is raised because status code is 201????

```
     try:
        task = bigip.task_start("/mgmt/tm/asm/tasks/import-policy", data=data)
    except Error as e:
        print(e)
```

```
Status:
201
Response Body:
{
    "isBase64": false,
    "policyType": "security",
    "status": "NEW",
    "name": "/Common/test-1-policy_clone",
    "lastUpdateMicros": 1702080711000000.0,
    "getPolicyAttributesOnly": false,
    "applicationLanguage": "utf-8",
    "kind": "tm:asm:tasks:import-policy:import-policy-taskstate",
    "selfLink": "https://localhost/mgmt/tm/asm/tasks/import-policy/KHjDkEgrrDlV56tnXYoZzA?ver=15.1.8",
    "sourcePolicyReference": {
        "link": "https://localhost/mgmt/tm/asm/policies/7R9un8f-kZ2rB9MyqWrP3Q?ver=15.1.8",
        "fullPath": "/Common/test-1-policy"
    },
    "startTime": "2023-12-09T00:11:51Z",
    "id": "KHjDkEgrrDlV56tnXYoZzA",
    "re...
```

**Comment by leonardobdes** [comment]
I am reopening this issue because it is a similar error.
However, it is not in the same method.

Did it work in a previous version of BIG-IP?
If yes, which version?
What is the full BIG-IP version?
I don't remember if the REST API gives the point release as well, so the error says 15.1.8, but it could be 15.1.8/15.1.8.1/15.1.8.2.

The questions above are mainly to understand if F5 made any changes to the REST API.
If they did, I can track the change and add not only 201 but other status codes.

**Comment by lrhazi** [comment]
I cannot tell if it was working before, as am writing a new script.
I upgraded to the latest 15: BIG-IP 15.1.10.2 Build 0.0.2 Point Release 2
and it seems to act the same way.  I am also getting the same results from the latest  BIG-IP version 17!!

**Comment by lrhazi** [comment]
I was looking at ansible f5 module... and it does seem to expect http code 201 and returns "id" and not "_id"

see line 512 here for example:

https://github.com/F5Networks/f5-ansible/blob/42d22465e93d449a102ff3a375ffcdff788d6eaf/ansible_collections/f5networks/f5_modules/plugins/modules/bigip_asm_policy_import.py

**Comment by lrhazi** [comment]
It looks like running tasks in asm module do not behave the same way as others? or at least this import-policy task.

See page 64 here:
https://cdn.f5.com/websites/devcentral.f5.com/downloads/icontrol-rest-api-user-guide-16-1-0.pdf

**Comment by leonardobdes** [comment]
Thanks for the troubleshooting and information.
Yes, the ASM task looks to work differently than other F5 modules, and unfortunately, that is common with F5 REST API.

Adding 201 status code will not fix the issue, as you already know.
"id_" is just a local variable for the task_start method, "_taskId" is what is expected to be in the response.
However, as you can see in your initial code and F5 documentation, the ASM response has "id".

This will be more complex to fix than just adding 201 status code.
I have to decide if I create a new method just for ASM or if I can modify the task_start method to be compatible with ASM.

I will think about it, test it in a lab, and then release a new version.

**Comment by leonardobdes** [comment]
Hi, sorry, but I will not be working more on this project.
If you still need help with your issue, please open an issue in this repository [https://github.com/f5-rahm/BIGREST](https://github.com/f5-rahm/BIGREST).
